### ISSUE TITLE
Should `/containers/{containerId}/foods/{foodId}` has `creaedAt`?

### ISSUE THREAD

**Issue by taniguchiiqqq** [genesis-tech-tribe/nishiki-documents#128]
## Your Question

Should PUT `/containers/{containerId}/foods/{foodId}` endpoint has `creaedAt` prop?
When a resource is updated, all props including unchanged ones should be sent to a endpoint. 

## Why are you asking?

CreatedAt prop is immutable, so I hesitate to make it look mutable.

## Additional Information

Any other internal context or references.

**Comment by hitohata** [comment]
In my humble opinion, I think It shouldn't add a `createdAt` attribute. It will be a cause of confusion.

**Comment by taniguchiiqqq** [comment]
@hitohata 
Thank you for your opinion. I won't add `createdAt` attribute.
