### ISSUE TITLE
Create GitHub Actions for deploying the OPEN API document

### ISSUE THREAD

**Issue by hitohata** [genesis-tech-tribe/nishiki-documents#18]
## Abstract

Create a new GitHub

## Description

To check the API Document on the browser, generate an HTML from the API document then host it on the GitHub pages.

## What should do

Create a GitHub Actions

**Comment by taniguchiiqqq** [comment]
The dir structure is supposed to be like the following.
/
├─docsaurus
│  └─built files
├─web-api
│  └─built files
└─index.html

and this dir structure may be placed in build dir when documents are built in a local env.
