### ISSUE TITLE
Create README.md for Nishiki GitHub Project

### ISSUE THREAD

**Issue by uskayyyyy** [genesis-tech-tribe/nishiki-documents#5]

**Comment by hitohata** [comment]
This issue looks duplicated to #3

**Comment by uskayyyyy** [comment]
@hitohata 
It's slightly different. When you create a new issue on a *Project*, you should not see the issue template created in each repository. The goal of this task is to figure out how to use issue templates on *Projects*.

**Comment by hitohata** [comment]
@uskayyyyy 
I see.
Sorry, I misunderstood.

**Comment by uskayyyyy** [comment]
@hitohata 
I'll change the title of this issue. It's misleading.

**Comment by uskayyyyy** [comment]
@hitohata
Actually I was misunderstanding. The purpose of this issue is to create a README.md for the Project Nishiki.
You can find it in the setting page of the Project. It is meant to explain what the project about and how to use it.
https://github.com/orgs/genesis-tech-tribe/projects/3/settings

Since this is a cross-repository issue, I created it as an issue of https://github.com/genesis-tech-tribe/nishiki-documents for now. Let me re-think where to place this issue.

**Comment by uskayyyyy** [comment]
Decided to migrate it to draft issue, which does not belong to any repository.
https://github.com/orgs/genesis-tech-tribe/projects/3/views/1?pane=issue&itemId=40900731
