### ISSUE TITLE
Add the AWS resource to the project document

### ISSUE THREAD

**Issue by hitohata** [genesis-tech-tribe/nishiki-documents#67]
## Describe the Enhancement

Add the AWS resource to the project document

## Page URL

None

## Why is this enhancement important?

To share the design of the AWS.

## Additional Context

None

**Comment by taniguchiiqqq** [comment]
@genesis-tech-tribe/initial-members 
IMO, if these three information `{system-name}-{env}-{resource-type}` are included, I don't have any more preference about naming convention. ie. `nishiki-backend-prod-igw`
but I prefer the kebab case and allow the name to use alphameric characters and dash.

**Comment by hitohata** [comment]
@taniguchiiqqq 
Thank you for commenting. Your strategy sounds great. I would like to adapt it as the naming convention in this project.
There are two name types in Cloud Formation, these are the logical name and the resource name.  (and there is a construct name in the CDK.)  And, I think the name you mention is the resource name. So, we need to get a consensus about the logical ID.
I think PascalCase is preferred for logical and configuration names. These names are listed on the Cloud Formation template. (The construct name turns to the logical name after the build process.). The CloudFormation template is PascalCase.
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/template-formats.html
