### ISSUE TITLE
Delete an SK of the he User and Group relations

### ISSUE THREAD

**Issue by hitohata** [genesis-tech-tribe/nishiki-documents#84]
## Describe the Problem

The User and Group relations' SK is set as User ID. But it's a duplicate and it can be retrieved because the User ID is also PK of the table. To optimize the performance and the cost, it's needed to remove the SK, which is the UserId attribute.

## What is Expected

Remove an SK of the User and Group relations.

## Screenshots

URL
https://genesis-tech-tribe.github.io/nishiki-documents/project-document/database#userandgrouprelations

## Browser/OS

None

## Additional Context

None

**Comment by taniguchiiqqq** [comment]
> it's a duplicate and it can be retrieved because the User ID is also PK of the table.

That's true! I can understand the point now. I appreciate your revise.
