### ISSUE TITLE
Can groupName be included at GET /containers/ ?

### ISSUE THREAD

**Issue by kotaaaa** [genesis-tech-tribe/nishiki-documents#89]
## Describe the consultation

- At GET /containers/, Can API response include not only groupId but groupName as well?
- I think this is not followed RESTful principle though,,,

**Comment by hitohata** [comment]
@kotaaaa 
Thank you for your suggestion and for updating the document. Thank you so much for real.

We discussed BFF and the Next can act as BFF using API function. Do you mean you cannot implement this function in the NEXT because of some reasons?
I don't remember the conclusion of that discussion on whether should we follow the RESTful philosophy or not. Do you remember about it?

In any case, the implementation itself is possible. My concern is the design of this system.

**Comment by kotaaaa** [comment]
Thank you for checking and sorry for late reply.

> We discussed BFF and the Next can act as BFF using API function. Do you mean you cannot implement this function in the NEXT because of some reasons?

After our conversation, I understood that we utilize REST API interface as much as possible.
I thought It means that, as a frontend perspective, it is enough to call REST API basically. but a few cases such as this issue cannot be satisfied by current REST interface.

If this is not implemented in REST interface, either frontend (Next.js) or Lambda is going to call these two REST endpoint instead, 

- GET /containers (1 times)
- GET /groups/{groupId} (n times)

The discussion point is where we should handle this logic.
- 1, Inside of backend of REST endpoint.
- 2, Server side of Next.js which calls No1 and No2 REST endpoint (I suppose this is what you meant as BFF above (the Next.js can act as BFF using API function))
- 3, GraphQL server which calls No1 and No2 REST endpoint
- 4, GraphQL server which calls directly DynamoDB

As my interest perspective, 3,4 would be candidate, there is no enough time for 1st release.

No2 can be possible but, asynchronous process handling will be a little complicated and network cost between frontend server and API gateway will arise (it might be trivia though).

Ideally, if this kind of data processing increases in the future, it would be better if it could be taken out to the middle layer between Backend and Frontend as "BFF" with Lambda or GraphQL.

What do you think?

**Comment by hitohata** [comment]
@kotaaaa 
Thank you for your explanation and sorry for replying late.
OK, I understood. Your idea is completely correct.
Therefore, let's add the group name in the /container endpoint.
